"""
Copyright (c) 2023 Aiven Ltd
See LICENSE for details
"""

from __future__ import annotations

from karapace.core.kafka.consumer import KafkaConsumer
from unittest.mock import patch


def test_create_group_id_custom_prefix() -> None:
    with patch("karapace.core.kafka.consumer.secrets.token_hex", return_value="deadbeefcafe"):
        assert KafkaConsumer._create_group_id("my-") == "my-deadbeefcafe"


def test_create_group_id_default_prefix() -> None:
    with patch("karapace.core.kafka.consumer.secrets.token_hex", return_value="deadbeefcafe"):
        assert KafkaConsumer._create_group_id("karapace-autogenerated-") == "karapace-autogenerated-deadbeefcafe"
