"""
Copyright (c) 2026 Aiven Ltd
See LICENSE for details
"""

from __future__ import annotations

from karapace.core.config import Config
from karapace.core.constants import DEFAULT_CONSUMER_GROUP_ID_PREFIX
from karapace.core.kafka.common import _KafkaConfigMixin
from karapace.core.kafka.consumer import AsyncKafkaConsumer, KafkaConsumer
from karapace.core.kafka_utils import kafka_consumer_from_config
from karapace.core.schema_reader import _create_consumer_from_config
from unittest.mock import MagicMock, patch

import logging
import re


class _ConfigCapture(_KafkaConfigMixin):
    """A helper exposing ``_get_config_from_params`` without connecting to Kafka."""

    def __init__(self) -> None:
        self._errors = set()
        self.log = logging.getLogger(__name__)


def test_create_group_id_custom_prefix() -> None:
    with patch("karapace.core.kafka.consumer.secrets.token_hex", return_value="deadbeefcafe"):
        assert KafkaConsumer._create_group_id("my-") == "my-deadbeefcafe"


def test_create_group_id_defaults_to_default_prefix() -> None:
    with patch("karapace.core.kafka.consumer.secrets.token_hex", return_value="deadbeefcafe"):
        assert KafkaConsumer._create_group_id() == "karapace-autogenerated-deadbeefcafe"


def test_config_default_prefix_is_karapace_autogenerated() -> None:
    config = Config()

    assert config.consumer_group_id_prefix == "karapace-autogenerated-"
    assert config.consumer_group_id_prefix == DEFAULT_CONSUMER_GROUP_ID_PREFIX


def test_schema_reader_consumer_group_id_uses_config_prefix() -> None:
    config = Config(consumer_group_id_prefix="my-prefix-")

    with patch("karapace.core.schema_reader.KafkaConsumer") as consumer_cls:
        _create_consumer_from_config(config)

    group_id = consumer_cls.call_args.kwargs["group_id"]
    assert group_id.startswith("my-prefix-")
    assert re.fullmatch(r"my-prefix-[0-9a-f]{12}", group_id)


def test_kafka_utils_consumer_group_id_uses_config_prefix() -> None:
    config = Config(consumer_group_id_prefix="my-prefix-")

    with patch("karapace.core.kafka_utils.KafkaConsumer") as consumer_cls:
        with kafka_consumer_from_config(config, topic="topic"):
            pass

    group_id = consumer_cls.call_args.kwargs["group_id"]
    assert group_id.startswith("my-prefix-")
    assert re.fullmatch(r"my-prefix-[0-9a-f]{12}", group_id)


def test_group_id_reaches_confluent_consumer_config() -> None:
    """The ``group_id`` parameter maps unchanged to the final confluent-kafka ``group.id`` setting."""
    config = Config(consumer_group_id_prefix="my-prefix-")

    with patch("karapace.core.schema_reader.KafkaConsumer") as consumer_cls:
        _create_consumer_from_config(config)
    kwargs = consumer_cls.call_args.kwargs

    confluent_config = _ConfigCapture()._get_config_from_params(**kwargs)

    assert confluent_config["group.id"] == kwargs["group_id"]
    assert confluent_config["group.id"].startswith("my-prefix-")


def test_kafka_consumer_does_not_prefix_explicit_group_id() -> None:
    captured_params: dict = {}

    def fake_init(self, bootstrap_servers, verify_connection=True, **params) -> None:
        captured_params.update(params)

    with patch.object(_KafkaConfigMixin, "__init__", fake_init):
        KafkaConsumer("broker:9092", group_id="explicit-group")

    assert captured_params["group_id"] == "explicit-group"


def test_async_consumer_does_not_prefix_explicit_group_id() -> None:
    """The REST proxy's consumer manager passes an explicit group id, which must not be prefixed."""
    async_consumer = AsyncKafkaConsumer("broker:9092", loop=MagicMock(), group_id="rest-proxy-group")

    with patch("karapace.core.kafka.consumer.KafkaConsumer") as consumer_cls:
        async_consumer._start()

    assert consumer_cls.call_args.kwargs["group_id"] == "rest-proxy-group"


def test_kafka_consumer_generates_group_id_with_default_prefix() -> None:
    captured_params: dict = {}

    def fake_init(self, bootstrap_servers, verify_connection=True, **params) -> None:
        captured_params.update(params)

    with patch.object(_KafkaConfigMixin, "__init__", fake_init):
        KafkaConsumer("broker:9092")

    assert re.fullmatch(r"karapace-autogenerated-[0-9a-f]{12}", captured_params["group_id"])


def test_empty_prefix_results_in_bare_token_hex_group_id() -> None:
    config = Config(consumer_group_id_prefix="")

    with patch("karapace.core.schema_reader.KafkaConsumer") as consumer_cls:
        _create_consumer_from_config(config)

    group_id = consumer_cls.call_args.kwargs["group_id"]
    assert re.fullmatch(r"[0-9a-f]{12}", group_id)
